"""Social-platform abstractions for rich channel adapters."""

from bub.social.capabilities import ActionConstraint, ChannelCapabilities, ContentConstraint, basic_channel_capabilities
from bub.social.types import (
    ActionKind,
    AdapterMode,
    Attachment,
    ContentKind,
    ConversationRef,
    ConversationSurface,
    CredentialKind,
    CredentialSpec,
    EventKind,
    InboundEvent,
    LiveSurfaceRef,
    MentionTarget,
    MentionTargetKind,
    OutboundAction,
    ParticipantRef,
    ProgressSurface,
    ProvisioningInfo,
    ProvisioningMode,
    ProvisioningState,
    ReplyGrant,
    ReplyMode,
    TransportKind,
    normalize_surface,
    to_primitive,
)

__all__ = [
    "ActionConstraint",
    "ActionKind",
    "AdapterMode",
    "Attachment",
    "ChannelCapabilities",
    "ContentConstraint",
    "ContentKind",
    "ConversationRef",
    "ConversationSurface",
    "CredentialKind",
    "CredentialSpec",
    "EventKind",
    "InboundEvent",
    "LiveSurfaceRef",
    "MentionTarget",
    "MentionTargetKind",
    "OutboundAction",
    "ParticipantRef",
    "ProgressSurface",
    "ProvisioningInfo",
    "ProvisioningMode",
    "ProvisioningState",
    "ReplyGrant",
    "ReplyMode",
    "TransportKind",
    "basic_channel_capabilities",
    "normalize_surface",
    "to_primitive",
]
